# Generated by Django 4.0.4 on 2022-05-07 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('movie_name', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('movie_name_en', models.TextField()),
                ('movie_year', models.TextField()),
                ('movie_rel_date', models.TextField()),
                ('movie_country', models.TextField()),
                ('movie_cate', models.TextField()),
                ('movie_rating', models.TextField()),
                ('movie_director', models.TextField()),
                ('movie_img', models.TextField()),
                ('movie_total_viewer', models.IntegerField()),
                ('movie_reserve', models.TextField()),
                ('movie_star', models.TextField()),
                ('movie_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_date', models.TextField()),
                ('res_movie', models.ForeignKey(db_column='res_movie', on_delete=django.db.models.deletion.PROTECT, to='movies.movie')),
                ('res_user', models.ForeignKey(db_column='res_user', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='moviedate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviedate_date', models.TextField()),
                ('moviedate_total_seat', models.IntegerField()),
                ('moviedate_reserve_seat', models.IntegerField()),
                ('moviedate_remain_seat', models.IntegerField()),
                ('moviedate_movie', models.ForeignKey(db_column='moviedate_movie', on_delete=django.db.models.deletion.PROTECT, to='movies.movie')),
            ],
        ),
    ]
