# Generated by Django 4.0.5 on 2022-07-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_no', models.IntegerField()),
                ('com_count', models.IntegerField()),
                ('mem_name', models.TextField()),
                ('video_name', models.TextField()),
                ('com_id', models.TextField()),
                ('comment', models.TextField()),
                ('comment_get', models.TextField()),
                ('commemt_get_day', models.TextField()),
                ('commemt_get_time', models.TextField()),
                ('sense', models.TextField()),
                ('sense_set', models.TextField()),
                ('sense_score', models.FloatField()),
            ],
        ),
    ]
